### ISSUE TITLE
Question: How could I utilize this with draft previews?

### ISSUE THREAD

**Issue by chandlervdw** [rexxars/picosanity-graphql#4]
I'd like to get draft previews but I want to avoid trying to maintain two separate `page` and `post` queries, as I'm utilizing GraphQL with sanity and don't want to have additional queries set up in GROQ. 

Any guidance here? Thanks in advance!

**Comment by rexxars** [comment]
Sorry, this is a bit too specific of a question - it depends on your setup, graphql schema, which frontend you are using etc. I'd suggest asking in the [Sanity slack](https://slack.sanity.io/).
